[package]
name = "sokoban-inator"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.3"
glam = "0.29.2"
hecs = "0.10.5"
itertools = "0.14.0"
rand = "0.9.0"
wasm = "0.0.0"
wasm-bindgen = "0.2.100"
